#a=open("seetha.txt","x")
x=open("seetha.txt","w")
x.write("iam seethalakshmi")
x.close()
b=open("seetha.txt","w")
b.write("iam studying python")
b.close()
y=open("seetha.txt","a")
y.write("\n hello")
y.close()
a=open("seetha.txt","r")
print(a.read())
a.close()
a=open("seetha.txt","r")
print(a.read(4))
a.close()
a=open("seetha.txt","r")
print(a.readline())
print(a.readline())
a.close()
