#a=open("sree.txt","x")
x=open("sree.txt","w")
x.write("hello")
x.close()
a=open("sree.txt","w")
a.write("iam studying python")
a.close()
y=open("sree.txt","a")
y.write("\n in futura labs")
y.close()
a=open("sree.txt","r")
print(a.read())
a.close()
a=open("sree.txt","r")
print(a.read(6))
a.close()
a=open("sree.txt","r")
print(a.readline())

print(a.readline())
a.close()
import os
os.remove("sree.txt")