x={"seetha","veni","mikhila","sree"}
print(x)
x={"seetha","veni","seetha","sree","mikhila"}
print(x)
x.add("priya")
print(x)
y={"akhil","amal","anoop","gokul"}
print(y)
x.update(y)
print(x)
a=x.union(y)
print(a)
w={"dog","cat","cow","horse"}
print(w)
f={"dog","hen","duck","parrot"}
print(f)
t=w.intersection(f)
print(t)
g=w.difference(f)
print(g)
f.remove("hen")
print(f)
f.discard("train")
print(f)
f.pop()
print(f)
f.clear()
print(f)
#del f
x=["mango","apple","orange","cherry"]
print(x)
x[3]="grapes"
print(x)
w=frozenset(x)
print(w)
'''w[1]="kiwi"
print(w)'''